### ISSUE TITLE
[UX] brick batch mode doesn't support -v and -w together

### ISSUE THREAD

**Issue by aspiers** [aergoio/aergo#103]
When running brick in batch mode (e.g. `brick foo.brick`), it supports `-v` for verbose logging, and `-w` for watching the file.  These are really useful options, but they cannot be used at the same time.

**Comment by sunpuyo** [comment]
The verbose mode showing the all information but the watch mode should show on important information to focus. Those are different so that they were not supported simultaneously.

However, there are a variety of use cases, so I will consider supporting both simultaneously.

**Comment by aspiers** [comment]
Thanks, both at once would be really useful.

**Comment by sunpuyo** [comment]
I add the feature to the develop branch 3080972a2015f04387461a778f82eac509612bfc

**Comment by aspiers** [comment]
Cool, thanks a lot! Will this appear in a new docker image automatically or do we have to wait for the next release?

**Comment by sunpuyo** [comment]
@graup Can you explain when commits 3080972a2015f04387461a778f82eac509612bfc to the develop branch are released?

**Comment by graup** [comment]
@aspiers @sunpuyo Develop branch will be released with the next minor release (2.2.0), currently scheduled for next week (Feb 13). Docker images will be updated automatically as soon as that version is out.

**Comment by aspiers** [comment]
Awesome, thanks a lot both :-)
