### ISSUE TITLE
libgmp.so can get built into libtool/lib64

### ISSUE THREAD

**Issue by aspiers** [aergoio/aergo#108]
`contract/vm.go` seems to assume that libgmp.so will always get built into `libtool/lib/`:

https://github.com/aergoio/aergo/blob/87a379a44bb03c8dc6f29e70732e5a1b297a9a1f/contract/vm.go#L13

but on my (openSUSE) system, it gets built in `libtool/lib64`:

```
libtool/lib:
total 1.5M
-rw-r--r-- 1 adam users 471K Feb  8 23:19 liblmdb.a
-rwxr-xr-x 1 adam users 306K Feb  8 23:19 liblmdb.so*
-rw-r--r-- 1 adam users 741K Feb  8 23:19 libluajit-5.1.a
drwxr-xr-x 3 adam users 4.0K Feb  3 19:45 lua/
drwxr-xr-x 2 adam users 4.0K Feb  8 23:19 pkgconfig/

libtool/lib64:
total 528K
-rwxr-xr-x 1 adam users  932 Feb  8 23:19 libgmp.la*
lrwxrwxrwx 1 adam users   16 Feb  8 23:19 libgmp.so -> libgmp.so.10.3.2*
lrwxrwxrwx 1 adam users   16 Feb  8 23:19 libgmp.so.10 -> libgmp.so.10.3.2*
-rwxr-xr-x 1 adam users 521K Feb  8 23:19 libgmp.so.10.3.2*
```

This results in a build error:

```
# github.com/aergoio/aergo/contract
gcc: error: contract/../libtool/lib/libgmp.so: No such file or directory
make[3]: *** [CMakeFiles/aergosvr.dir/build.make:57: CMakeFiles/aergosvr] Error 2
make[2]: *** [CMakeFiles/Makefile2:260: CMakeFiles/aergosvr.dir/all] Error 2
make[1]: *** [Makefile:84: all] Error 2
make: *** [Makefile:32: all] Error 2
```

Changing the above line in `contract/vm.go` to:

```Make
#cgo !darwin,!windows LDFLAGS: ${SRCDIR}/../libtool/lib/libluajit-5.1.a ${SRCDIR}/../libtool/lib64/libgmp.so -lm
```

fixes the build, but presumably the `lib64` component should be obtained dynamically from somewhere rather than just hardcoding it.  I'm not sure if this is a problem on a lot of 64-bit Linux systems, or if there is something slightly different about mine vs. say, Ubuntu or Fedora.  But either way, making assumptions about the value seems unreliable.

**Comment by graup** [comment]
Maybe @hayarobi @eve2adam can have a look this

**Comment by eve2adam** [comment]
What is the opensuse Linux version? I have successfully built opensuse leap 15.2 in Docker.

**Comment by aspiers** [comment]
I'm using openSUSE Tumbleweed (the rolling release version of the distribution) but it should be similar to 15.2.

**Comment by aspiers** [comment]
Any thoughts on this?  I still see the problem.  I found a slightly similar report in this other project: https://github.com/spack/spack/issues/10842

I think this is due to "biarch" or "multilib" distributions which simultaneously supports 64-bit (in `lib64/` subdirectories) and 32-bit (in `lib/`):

- https://en.opensuse.org/openSUSE:Packaging_Conventions_RPM_Macros#.25_lib
- https://doc.opensuse.org/documentation/leap/archive/42.1/reference/html/book.opensuse.reference/cha.64bit.html

@eve2adam I see the same thing in the 15.2 Docker image:

    docker run --rm opensuse/leap:15.2 rpm --eval '%{_lib}'  

so I'm curious to know how yours built successfully.  Maybe you can share the steps to reproduce?

**Comment by eve2adam** [comment]
i built successfully with interactive mode at opensuse/leap:15.2 after your reply
hm.. the step is below
>zypper install --type pattern devel_basis
>zypper install git cmake
>download golang 1.13.x
>export GOPATH
>go get -d github.com/aergoio/aergo
>cd $AERGOHOME
>git submodule init && git submodule update
>make

you still have problem, so i'll fix the compile option to  -L${SRCDIR}/../libtool/lib -L${SRCDIR}/../libtool/lib64 -lgmp

**Comment by aspiers** [comment]
[**@eve2adam**](https://github.com/eve2adam) commented on [April 13, 2020 11:18 AM](https://github.com/aergoio/aergo/issues/108#issuecomment-612842036 "2020-04-13T10:18:50Z - Replied by Github Reply Comments"):
> you still have problem, so i'll fix the compile option to  -L${SRCDIR}/../libtool/lib -L${SRCDIR}/../libtool/lib64 -lgmp

Thanks, that's a nice idea.  It might be slightly better if `lib64` comes first, but I'm not 100% sure - maybe it doesn't make any difference ;-)

**Comment by eve2adam** [comment]
commited at 79484c20b752081a6e41ef0957551b57174cbe54
