### ISSUE TITLE
brick doesn't make it obvious where errors are coming from

### ISSUE THREAD

**Issue by aspiers** [aergoio/aergo#113]
When brick fails due to errors in Lua, it outputs errors like this:

    ERR execution fail error="[string \"0cca71fcf76698693693c6edc703ea42c82494bfafa1b6a14100aabaa7a1afb08f\"]:27: expected string but got nil" cmd=call module=brick

This looks like a bug; presumably the `[string \"...\"]` bit is supposed to be a line number and 27 is the column number?  This makes it a lot harder to debug problems in Lua.

**Comment by sunpuyo** [comment]
That is the contract ID of the deployed source, followed by the line number 27.

**Comment by aspiers** [comment]
Ah OK, thanks!  Yes it would be better if the contract id was decoded to look the same as aergoscan and everywhere else.  This would be a very good first step.

**Comment by aspiers** [comment]
Would it be possible for brick to show the 10 lines of context in the code around the line number with the error?  This would be especially helpful when the contract is compiled with ship and the line numbers are different to the original source files due to imports being included.

**Comment by kroggen** [comment]
Probably related to [this line](https://github.com/aergoio/aergo/blob/develop/contract/vm.go#L1344)

Possible fix would be to use `types.EncodeAddress(id)` instead of `hex.EncodeToString(id)`
