### ISSUE TITLE
brick expected_query_result assumes deterministic ordering of table keys

### ISSUE THREAD

**Issue by aspiers** [aergoio/aergo#119]
brick allows querying a smart contract and checking for an expected result:

    query <contract_name> <func_name> <query_json_str> [expected_query_result] [expected_error]

(As mentioned in #104 it would be great if this was also possible for `call`, but that is a separate issue.)

However, if the query returns a Lua table, then the ordering of the keys is not deterministic, so it's possible to get a false error like:

    ERR execution fail error="expected: {\"a\":1,\"b\":2}, but got: {\"b\":2,\"a\":1}" cmd=query module=brick

Of course it's possible to modify the smart contract to convert this to a lua "list" (ordered table), e.g.

    {
        [1]={"key":"a","value":1},
        [2]={"key":"a","value":2},
    }

and then compare against that, but this is not just a painful developer experience but might also go against the requirements of what the ABI needs to expose to the contract caller.  So it would be nicer if there was an easier way to do the comparison which was built-in.

**Comment by aspiers** [comment]
Hmm, I guess brick was never supposed to be a sophisticated automated testing framework.  Another example where comparisons don't work is when the return result is non-deterministic by including values returned from `system.getTimestamp()`.  So maybe the only solution in these cases is to test using one of the hera* SDKs on a real blockchain - but unfortunately that is a lot slower.

**Comment by kroggen** [comment]
On my tests the ordering of the keys is alphabetical, so it is deterministic
