### ISSUE TITLE
aergocli contract deploy missing docs for optional deployment arguments

### ISSUE THREAD

**Issue by aspiers** [aergoio/aergo#121]
`aergocli` can be used to deploy a contract with arguments:

    aergocli contract deploy <creator> <bcfile> <abifile> [args]

However AFAICS the final optional `args` parameter is not documented anywhere; I had to hunt for it in the source code:

https://github.com/aergoio/aergo/blob/58325ca10f310e646fa345ab478bfd25df743076/cmd/aergocli/cmd/contract.go#L112

For some reason, I can't even get `aergocli` to print this usage message even if I try.  And the CLI output doesn't mention it either:

    $ aergocli contract deploy
    Error: requires at least 1 arg(s), only received 0
    Usage:
      aergocli contract deploy [flags] --payload 'payload string' creator
      aergocli contract deploy [flags] creator bcfile abifile

    Flags:
          --amount string     setting amount (default "0")
      -h, --help              help for deploy
          --password string   Password
          --path string       Path to account data directory (default "$HOME/.aergo/data")
          --payload string    result of compiling a contract
      -r, --redeploy string   redeploy the contract

    Global Flags:
          --config string          config file (default is cliconfig.toml)
      -g, --gaslimit uint          Gas limit
          --home string            aergo cli home path
      -H, --host string            Host address to aergo server (default "localhost")
      -p, --port int32             Port number to aergo server (default 7845)
          --tlscacert string       aergosvr CA certification file for TLS
          --tlscert string         client certification file for TLS
          --tlskey string          client key file for TLS
          --tlsservername string   aergosvr name for TLS

So I think it needs to be added to the docs as well as this usage text.

Actually, `aergocli contract deploy` is not even documented at all at https://docs.aergo.io/en/latest/tools/aergocli.html#usage

**Comment by graup** [comment]
Hi @aspiers, thanks for catching that. I tried to improve the deploy and call usage texts a bit, could you check if this improves things? https://github.com/aergoio/aergo/pull/122

**Comment by graup** [comment]
I just merged this to make it into the 2.2 release. Let me know if we can improve the cli help more.

**Comment by aspiers** [comment]
Thanks a lot Paul - I tested and it looks great to me now! :+1:
