### ISSUE TITLE
Smart contracts: convert between address and public key

### ISSUE THREAD

**Issue by kroggen** [aergoio/aergo#142]
Suggestion for smart contracts: a function (or 2) to convert between an aergo address and the associated public key

```
address <-> pubkey
```

This is useful when we have content that was signed outside of Aergo (other networks or apps) and so we have only the public key, but we need the corresponding aergo address to verify the signature

**Comment by graup** [comment]
When you say address, I assume you mean a base58check encoded string?

`address: string = base58checkEncode([0x42, pubkey.x, pubkey.y])`

`pubkey = base58checkDecode(address).slice(1)`

**Comment by kroggen** [comment]
Yes. Currently we do not have a function for this on smart contracts.

So you suggest to make this conversion prior to sending the data to the smart contract?

It makes sense. But having it ready on the smart contract would be easier for developers to use. They don't need to implement this on each different programming language. Unless we export this on the wrappers (heraxx, libaergo...)

The main goal of this feature is to be able to upload messages from existing applications and verify the signatures on the smart contract, without the need to modify these applications.
