### ISSUE TITLE
Decimal Support: 9 or 18

### ISSUE THREAD

**Issue by ashen1dev** [aergoio/aergo#16]
'AERGO' is main coin of Aergo Network. One advantage of cryptocurrency is that it can be divided smaller than the base unit.(Better Liquidity) and we want to define the minimum unit called AER. Aergo's smart contracts, SDK and AergoCLI will  use AER as a basic unit. The problem is how much AER is smaller than AERGO. In initial discussion, we noticed that most Ether wallets actually use the GWei unit as a fee unit.

So we tried to define AER to be 10 ^ -9 of AERGO (until Release 0.8.1). But soon, we found the compatibility problem. In case of the ERC20 token transfer from the Ethereum to AERGO main network(via the Asset Bridge), token value will be truncated from 18 decimals to 9 decimals.

We will define AER as 10 ^ -18. However, in this case, we need to implement a separate big number data structure instead of using unsigned int 64 bits.

In addition, it is also better to be compatible with Ethereum by supporting up to 10 ^ -18 in terms of 'Forward Compatibility'.

**Comment by graup** [comment]
For compatibility reasons, I think it makes sense to stick with 18 digits. There are even some proposals to make that compulsory for all ERC20 tokens (https://github.com/ethereum/EIPs/issues/724), but anyway it is the de-facto standard.

We'll need to refactor all code regarding balances and transaction amounts in the server and all clients.

**Comment by graup** [comment]
[x] Herajs merged support for 18 decimals in https://github.com/aergoio/herajs/commit/7435563b9679b4816010beb03ad89e7b14f87b71

**Comment by ashen1dev** [comment]
We decided to go on 18 decimals.
