### ISSUE TITLE
Upgrade libgmp to 6.2.1

### ISSUE THREAD

**Issue by hayarobi** [aergoio/aergo#172]
Currently the Aergo references libgmp-6.1.2. How about raising this to 6.2.1?

Currently, build fails on apple silicon mac, but make can succeed if libgmp is upgraded to 6.2.1. I know that Aergo officially supports only linux, but it is possible to perform basic build checks in other OSs, and to test functions such as consensus, rpc, and p2p are possible.

I read release notes of libgmp-6.2.1, it says that it is backwards compatible with the previous versions, except when one semi-documented function -mpn_bdivmod- is used. So, I don't think it's impossible to upgrade.

https://gmplib.org/gmp6.2

-----------------------------

현재 Aergo가 참조하는 libgmp는 버전이 6.1.2입니다. 이것을 6.2.1로 올리는 것은 어떨지요?
현재는 Apple Silicon Mac에서 빌드가 실패하지만, libgmp을 6.2.1로 업그레이드를 하면 make가 성공할 수 있습니다. Aergo가 공식적으로는 linux만 지원하는 것은 맞지만, 다른 OS에서도 기본적인 빌드 검사를 할 수도 있고, consensus나 rpc, p2p등의 기능 테스트는 가능할 것으로 봅니다.

일단 libgmp-6.2.1의 릴리즈 노트를 보면 mpn_bdivmod 함수 하나를 사용하는 경우 외에는 기존 버전과 하위호환이 된다고 나와있습니다. 그래서 업그레이드가 불가능하지는 않을 것 같긴 합니다. 

https://gmplib.org/gmp6.2

**Comment by kroggen** [comment]
Implemented on [this PR](https://github.com/aergoio/aergo/pull/205)

I suspect this can be closed
