### ISSUE TITLE
Add block size to API

### ISSUE THREAD

**Issue by graup** [aergoio/aergo#73]
Please add a field `size` to both `BlockMetadata` and `Block`, included in the return types of `ListBlockMetadata`, `ListBlockMetadataStream`, `GetBlockMetadata`, `GetBlock`, `ListBlockStream`.

The field should contain the value returned by [`block.Size()`](https://github.com/aergoio/aergo/blob/b56738252fd8ebfda47f41fe28d30d19c65126c4/types/blockchain.go#L334) or similar.

Question: The referenced method Size() seems to loop over all transactions, I wonder if that is very efficient. Maybe there is a more efficient way?

**Comment by qcollapse** [comment]
As described in the comment of the method, it does not return the real size of a marshaled block.

If you want it, you should use `proto.Size`.

**Comment by graup** [comment]
@qcollapse yes that sounds like the better option.

**Comment by graup** [comment]
Actually we don't need to add it to the `Block` type then – clients can just compute it themselves since that object contains all the data. Let's only add it to `BlockMetadata`.
