### ISSUE TITLE
`Lua-JIT` as a blockchain virtual machine

### ISSUE THREAD

**Issue by yejiayu** [aergoio/aergo#86]
Hi

I saw the use of `Lua-JIT` as a virtual machine in the documentation, so how do you solve the problem that the `gas` consumption between each node in the `JIT` environment may be inconsistent?

Thanks.

**Comment by mlogue76** [comment]
That's a good point.
Machine codes created by the JIT optimizer can vary from machine to machine.
So the JIT optimizer is now disabled.
It is under study for use in private networks.
Thank you.
