### ISSUE TITLE
grpc "GetTx" returns an error

### ISSUE THREAD

**Issue by mymixing** [aergoio/aergo#87]
Grpc GetTx returns an error
GetTX: <nil> rpc error: code = NotFound desc = not found

The same txhash
Grpc GetReceipt returns success
Current aergo version 1.2.0

**Comment by kjunu** [comment]
What kind of tx do you send? can i see that tx contents?

**Comment by mymixing** [comment]
> What kind of tx do you send? can i see that tx contents?
tx: FzNSs53vDwUQ2Yh7PzWxWwpcvrJZnkQQ9dRRB6ZAYqp2

**Comment by mymixing** [comment]
@kjunu 

> What kind of tx do you send? can i see that tx contents?
tx: FzNSs53vDwUQ2Yh7PzWxWwpcvrJZnkQQ9dRRB6ZAYqp2

**Comment by mymixing** [comment]
@kjunu 
With GetTx, any txhash will return an error

error: code = NotFound desc = not found

**Comment by mymixing** [comment]
@kjunu 
With GetTx, any txhash will return an error

error: code = NotFound desc = not found

相同的txhash, GetReceipt returns success

**Comment by kjunu** [comment]
Which full node do you use? I can GetTx with my node.
It may not be displayed properly while syncing.

**Comment by mymixing** [comment]
@kjunu 
I am using "mainnet-api.aergo.io:7845"
this is an official node

**Comment by mymixing** [comment]
@kjunu this is my code

`package main

import (
	"context"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"github.com/aergoio/aergo/cmd/aergocli/util"
	"github.com/aergoio/aergo/types"
	"github.com/anaskhan96/base58check"
	"github.com/mr-tron/base58"
	"google.golang.org/grpc"
	"math/big"
)

var (
	client *util.ConnClient
)

func GetBlock(){
	var blockQuery []byte
	b := make([]byte, 8)
	binary.LittleEndian.PutUint64(b, uint64(8645386))
	blockQuery = b
	block, err := client.GetBlock(context.Background(), &types.SingleBytes{Value: blockQuery})


	fmt.Println("GetBlock:", base58.Encode(block.Hash), block, err)
	for _, tx := range block.Body.Txs {

		encoded, _ := base58check.Encode(fmt.Sprintf("%x", 0x42), hex.EncodeToString(tx.Body.Account))
		fmt.Println("GetBlock tx:", base58.Encode(tx.Hash))
		fmt.Println("GetBlock Account:", encoded)
		fmt.Println("GetBlock Recipient:", base58.Encode(tx.Body.Recipient))
		fmt.Println("GetBlock Amount:", big.NewInt(0).SetBytes(tx.Body.Amount))
		fmt.Println("GetBlock GasPrice:", big.NewInt(0).SetBytes(tx.Body.GasPrice))
	}
}

func Blockchain(){
	Blockchain, err := client.Blockchain(context.Background(), &types.Empty{})
	fmt.Println("Blockchain:", Blockchain, err)
}

func GetTX(){
	txHash, _ := base58.Decode("FzNSs53vDwUQ2Yh7PzWxWwpcvrJZnkQQ9dRRB6ZAYqp2")
	tx, err := client.GetTX(context.Background(), &types.SingleBytes{Value: txHash})
	fmt.Println("GetTX:", tx, err)
}

func GetReceipt(){
	txHash, _ := base58.Decode("FzNSs53vDwUQ2Yh7PzWxWwpcvrJZnkQQ9dRRB6ZAYqp2")
	receipt, err := client.GetReceipt(context.Background(), &types.SingleBytes{Value: txHash})
	fmt.Println("GetReceipt:", receipt, err)
	fmt.Println("GetReceipt feeUsed:", big.NewInt(0).SetBytes(receipt.FeeUsed))
}

func main() {
	GetTX()
	GetReceipt()
}

func init(){
	ok := true
	opts := []grpc.DialOption{
		grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(1024 * 1024 * 256)),
	}

	opts = append(opts, grpc.WithInsecure())

	client, ok = util.GetClient("mainnet-api.aergo.io:7845", opts).(*util.ConnClient)
	if ok != true {
		panic("GetClient faild")
	}
}`

**Comment by kjunu** [comment]
GetTx GRPC only search in mempool. in your case tx is already included in block. so you should use GetBlockTx.

**Comment by mymixing** [comment]
oh, thank you @kjunu 
GetBlockTx Got the result I want
