### ISSUE TITLE
I have 4 questions about using cli

### ISSUE THREAD

**Issue by mymixing** [aergoio/aergo#89]
I have 4 questions about using cli
1. How to send a sum aego transfer
2. How to check the aergo balance
3. How to send a contract tansfer
4. How to check the contract balance

**Comment by kjunu** [comment]
1 sendtx
2 getstate
3 sendtx or contract
4 getstate

here is some doc :)

1, 2, 4 : https://docs.aergo.io/en/1.2/tools/aergocli.html
3 : https://docs.aergo.io/en/1.2/smart-contracts/lua/hello-world.html

**Comment by mymixing** [comment]
@kjunu 
I want to ask
https://mainnet.aergoscan.io/transaction/4THbCA8Wv2ExK8aAaVEeK6ypxxiYamQN2cARZknZTZuM

why am I using:
docker run --rm aergo/tools aergocli -H mainnet-api.aergo.io contract abi AmPw8QLaGkd96GAYfuh9ASQB2FaK8BBUbfxArU4PrG43UMbPiKPm

response:
2019/08/14 03:35:40 rpc error: code = Unknown desc = cannot find contract

what is the contract in https://mainnet.aergoscan.io/transaction/4THbCA8Wv2ExK8aAaVEeK6ypxxiYamQN2cARZknZTZuM

**Comment by kjunu** [comment]
Because AmPw8QLaGkd96GAYfuh9ASQB2FaK8BBUbfxArU4PrG43UMbPiKPm is not a contract address

If you want to test the get contract ABI try this address in mainnet "AmhJX1FYQKqNuhwBACW7fkxcTHdMakAfMQobuD5QNXJwT1ZgriAc"

https://mainnet.aergoscan.io/account/AmhJX1FYQKqNuhwBACW7fkxcTHdMakAfMQobuD5QNXJwT1ZgriAc

**Comment by mymixing** [comment]
@kjunu 
e...
what is the contract in https://mainnet.aergoscan.io/transaction/4THbCA8Wv2ExK8aAaVEeK6ypxxiYamQN2cARZknZTZuM?

**Comment by kjunu** [comment]
It's not aergo contract calling tx. someone just send tx with payload.

**Comment by mymixing** [comment]
@kjunu 
how can I tell if a Transaction is an aergo transaction or a contract transaction or something else?

**Comment by kjunu** [comment]
The contract calling transaction has a json-formatted payload like this https://mainnet.aergoscan.io/transaction/9XEsK47QLQQpHiWNmeGp4qH79wydXQAb377EVD4SsFrh/?payload=json

You can guess by looking at the payload. but to be clear, you need to check the history
