### ISSUE TITLE
[CLI] should coinbase address be encoded as base58check(AddressVersion + Address) ?

### ISSUE THREAD

**Issue by hanlsin** [aergoio/aergo#91]
The coinbase address in the block information is currently just encoded as `base58`.

Is it correct? Should it be encoded as (AddressVersion + base58check)?

https://github.com/aergoio/aergo/blob/35879e34e615f2498a31381ffa97160e98211379/cmd/aergocli/util/base58addr.go#L243

Related issue
https://github.com/aergoio/herapy/issues/70

**Comment by kjunu** [comment]
It seems to be a mistake. I'll check and fix some more. thanks :)

**Comment by hanlsin** [comment]
Please check "hera" series for this issue.

If there are all fine, then I will close this.

@graup Would you please advice me or invite who is responsible for heraj?

**Comment by acktsap** [comment]
heraj is on me. In heraj, it's already printed as base58check (including address version).

**Comment by graup** [comment]
@kjunu has this been fixed in aergo?

**Comment by kjunu** [comment]
yes :) 

https://github.com/aergoio/aergo/commit/9f06ae6ce9eb0ac0179b93d7c633fe0d370788ea
