### ISSUE TITLE
[V2] need to check TxType_TRANSFER?

### ISSUE THREAD

**Issue by hanlsin** [aergoio/aergo#92]
I have a question for checking TX type in the below code of V2.

https://github.com/aergoio/aergo/blob/97c73a8408e54f36b8b0cb85c9d41da2797cc585/contract/contract.go#L221

Token transfer TX is also changed to TxType_TRANSFER, right?

If yes, should the above code check TRANSFER too?

Why does it need to keep NORMAL, btw?

**Comment by mlogue76** [comment]
1. TRANSFER
Good point. I forgot the type check.

2. NORMAL
We keep the NORMAL type for backward compatibility.

**Comment by hanlsin** [comment]
https://github.com/aergoio/aergo/blob/97c73a8408e54f36b8b0cb85c9d41da2797cc585/types/transaction.go#L310

Miss checking the type, 'TxType_TRANSFER'.

Without it, an insufficient tx would remain in Mempool permanently.

**Comment by mlogue76** [comment]
It was fixed at 273d0bd4

**Comment by graup** [comment]
Closing as this seems to be resolved. Feel free to reopen if there are any further problems.
