### ISSUE TITLE
[V2] Is there any way to distinguish between V1 and V2 when connect?

### ISSUE THREAD

**Issue by hanlsin** [aergoio/aergo#93]
To support both versions in the SDKs, it would be better to know about a node connected is V1 or V2.

For example, after connecting V2 and then if "rpc.GetServerInfo" returns a differentiable value such as "fork_version=2", the SDK can support both versions.

Without it, a client using V2 SDKs cannot communicate the older version (V1) node. Making the client to use V1 SDKs causes that newer features should be included in the older version and release it.

The current "version" field seems not enough to separate them.

**Comment by graup** [comment]
Do you have an example of where this could be a problem? As far as I can tell, most changes on the API level are backwards compatible.

**Comment by hanlsin** [comment]
When a client using a V2 SDK tried to use a V1 node, we can recommend

1. upgrade the node as V2, or
2. use V1 SDK

But, if SDKs support V1 and V2, then it would be easier for maintaining the client.

It seems not a general occasion at the moment and not a normal approach, of course, so I am just proposing it.

**Comment by mlogue76** [comment]
You can use a  `chainid.version` through `rpc.Blockchain` or `rpc.GetChainInfo` since 3eb19648

If there is no `chainid.version` in the result,` chainid.version` is 0.

**Comment by graup** [comment]
Looks like this is supported no. Closing this issue, feel free to reopen.
